server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/




spring:
  application:
    name: MyHouse-Email #该服务在注册中心的名字
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

  # 上传文件总的最大值
  http:
    max-file-size: 50MB
    max-request-size: 50MB
    enabled: false
# 上传文件的存放路径
fileUpload:
  filepath: "\\MyHouse-Email\\src\\main\\resources\\email\\file\\"
  imgPath:  "\\MyHouse-Email\\src\\main\\resources\\email\\img\\"

mybatis-plus:
  mapper-locations: classpath:com/xw/*/mapper/xml/*.xml
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    jdbc-type-for-null: 'null'